// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// frsr
DataFrame frsr(DataFrame input, bool keep_params);
RcppExport SEXP _frsrr_frsr(SEXP inputSEXP, SEXP keep_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type input(inputSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_params(keep_paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(frsr(input, keep_params));
    return rcpp_result_gen;
END_RCPP
}
// phase_orchestrator
List phase_orchestrator(int phases, IntegerVector exponents, int per_cell, IntegerVector magics, double q, int NRmax);
RcppExport SEXP _frsrr_phase_orchestrator(SEXP phasesSEXP, SEXP exponentsSEXP, SEXP per_cellSEXP, SEXP magicsSEXP, SEXP qSEXP, SEXP NRmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type phases(phasesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type exponents(exponentsSEXP);
    Rcpp::traits::input_parameter< int >::type per_cell(per_cellSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type magics(magicsSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type NRmax(NRmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(phase_orchestrator(phases, exponents, per_cell, magics, q, NRmax));
    return rcpp_result_gen;
END_RCPP
}
// sample_inputs
NumericVector sample_inputs(int n, double x_min, double x_max, const std::string& method);
RcppExport SEXP _frsrr_sample_inputs(SEXP nSEXP, SEXP x_minSEXP, SEXP x_maxSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type x_min(x_minSEXP);
    Rcpp::traits::input_parameter< double >::type x_max(x_maxSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_inputs(n, x_min, x_max, method));
    return rcpp_result_gen;
END_RCPP
}
// search_optimal_constant
DataFrame search_optimal_constant(NumericVector floats, IntegerVector magics, int NRmax, std::string objective_metric, std::string dependent_metric);
RcppExport SEXP _frsrr_search_optimal_constant(SEXP floatsSEXP, SEXP magicsSEXP, SEXP NRmaxSEXP, SEXP objective_metricSEXP, SEXP dependent_metricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type floats(floatsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type magics(magicsSEXP);
    Rcpp::traits::input_parameter< int >::type NRmax(NRmaxSEXP);
    Rcpp::traits::input_parameter< std::string >::type objective_metric(objective_metricSEXP);
    Rcpp::traits::input_parameter< std::string >::type dependent_metric(dependent_metricSEXP);
    rcpp_result_gen = Rcpp::wrap(search_optimal_constant(floats, magics, NRmax, objective_metric, dependent_metric));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_frsrr_frsr", (DL_FUNC) &_frsrr_frsr, 2},
    {"_frsrr_phase_orchestrator", (DL_FUNC) &_frsrr_phase_orchestrator, 6},
    {"_frsrr_sample_inputs", (DL_FUNC) &_frsrr_sample_inputs, 4},
    {"_frsrr_search_optimal_constant", (DL_FUNC) &_frsrr_search_optimal_constant, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_frsrr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
