# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

frsr <- function(input, keep_params) {
    .Call(`_frsrr_frsr`, input, keep_params)
}

phase_orchestrator <- function(phases, exponents, per_cell, magics, q, NRmax) {
    .Call(`_frsrr_phase_orchestrator`, phases, exponents, per_cell, magics, q, NRmax)
}

bounded_stratified_sample <- function(n, low, high, weighted) {
    .Call(`_frsrr_bounded_stratified_sample`, n, low, high, weighted)
}

search_optimal_constant <- function(floats, magics, NRmax, objective_metric, dependent_metric) {
    .Call(`_frsrr_search_optimal_constant`, floats, magics, NRmax, objective_metric, dependent_metric)
}

