# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

frsr <- function(input, keep_params) {
    .Call(`_frsrr_frsr`, input, keep_params)
}

phase_orchestrator <- function(phases, exponents, per_cell, magics, q, NRmax) {
    .Call(`_frsrr_phase_orchestrator`, phases, exponents, per_cell, magics, q, NRmax)
}

sample_inputs <- function(n, x_min, x_max, weighted, method) {
    .Call(`_frsrr_sample_inputs`, n, x_min, x_max, weighted, method)
}

search_optimal_constant <- function(floats, magics, NRmax, objective_metric, dependent_metric) {
    .Call(`_frsrr_search_optimal_constant`, floats, magics, NRmax, objective_metric, dependent_metric)
}

